server:
  port: 9207

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9761/eureka/

spring:
  datasource:
    url: jdbc:mysql://condonuity-prod-db.mysql.database.azure.com:3306/condonuityuat?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: condonuity@condonuity-prod-db
    password: '{cipher}e0601cc852475108016ddb3d2907a08eacd8735d8b0d9d10ac02317091c21c33'


#spring:
#  datasource:
#    url: jdbc:mysql://condonuitydev.mysql.database.azure.com:3306/condonuitydev?serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: condonuitydbuser@condonuitydev
#    password: '{cipher}c822ef0dae34f3ed01d913f277528d004a6f2a090cdb1f18ebe7f33553446d02'
#    url: jdbc:mysql://localhost:3306/security_services_condonuity?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password:
#    driver-class-name: com.mysql.jdbc.Driver

baseUrl: 'https://uatapp.condonuity.ca/'

spring.jpa:
  hibernate:
    connection:
      charset: utf8
      useUnicode: true
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
