server:
  port: 8205

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

azure:
  storage:
    ConnectionString: DefaultEndpointsProtocol=https;AccountName=condonuitystorageuat;AccountKey=7sj7qj6fP4Bv1B+1fVXRmYKoD0J9PVHaVWoGu34rYiJOwHH2IY9jRocXB2FGY8i3+foWVQz4oVa+qT+6/vuSQw==;EndpointSuffix=core.windows.net
    container:
      name: condonuitystorageuat


spring:
  datasource:
    url: jdbc:mysql://condonuityuatdb.mysql.database.azure.com:3306/condonuityuat?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: condonuity@condonuityuatdb
    #password: '{cipher}cb6c724122a20431a2dd653d6446ce8f80dad820865703652eed428f1af86c1a'
    password: Condo$12345

#spring:
#  datasource:
#    url: jdbc:mysql://condonuitydev.mysql.database.azure.com:3306/condonuitydev?serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: condonuitydbuser@condonuitydev
#    password: '{cipher}c822ef0dae34f3ed01d913f277528d004a6f2a090cdb1f18ebe7f33553446d02'
    # servlet:
    #   multipart:
    #     enabled: true
    #     max-file-size: 512MB
    #     max-request-size: 512MB

spring.jpa:
  hibernate:
    connection:
      charset: utf8
      useUnicode: true
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true
