server:
  port: 8205

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

azure:
  storage:
    ConnectionString: DefaultEndpointsProtocol=https;AccountName=condonuityuatstorage;AccountKey=18/P5Cw2Py/d6dreb5Dlus/K6OMUkAd7PjO6hW6Ey/6Bz6mKUqWYKKjtl7SDfT8xj2EfUeKJNwv0HjRQiJXkoA==;EndpointSuffix=core.windows.net
    container:
      name: condonuityuatstorage


spring:
  datasource:
    url: jdbc:mysql://condonuity-uat-db.mysql.database.azure.com:3306/condonuityuat?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: condonuity@condonuity-uat-db
    password: '{cipher}798161371b66572a9dce2303c9236bf83d161e5b1ed797dba762828907b24198'

#spring:
#  datasource:
#    url: jdbc:mysql://condonuitydev.mysql.database.azure.com:3306/condonuitydev?serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: condonuitydbuser@condonuitydev
#    password: '{cipher}c822ef0dae34f3ed01d913f277528d004a6f2a090cdb1f18ebe7f33553446d02'
    # servlet:
    #   multipart:
    #     enabled: true
    #     max-file-size: 512MB
    #     max-request-size: 512MB

spring.jpa:
  hibernate:
    connection:
      charset: utf8
      useUnicode: true
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true
