server:
  port: 8205

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

azure:
  storage:
    ConnectionString: DefaultEndpointsProtocol=https;AccountName=condonuitystorage;AccountKey=E1MlKVjVd3PXPnpdr5OqbpXjZzBeS6mc15Bxpvi4ljQQFUrxAK+qd/+KyZUtL4r33EQwnilvlvRLVrCAcz57qg==;EndpointSuffix=core.windows.net
    container:
      name: condonuitystorage


spring:
  datasource:
    url: jdbc:mysql://condonuity-prod-db.mysql.database.azure.com:3306/condonuity?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: condonuity@condonuity-prod-db
    password: '{cipher}e0601cc852475108016ddb3d2907a08eacd8735d8b0d9d10ac02317091c21c33'


#spring:
#  datasource:
#    url: jdbc:mysql://condonuitydev.mysql.database.azure.com:3306/condonuitydev?serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: condonuitydbuser@condonuitydev
#    password: '{cipher}c822ef0dae34f3ed01d913f277528d004a6f2a090cdb1f18ebe7f33553446d02'
    # servlet:
    #   multipart:
    #     enabled: true
    #     max-file-size: 512MB
    #     max-request-size: 512MB

spring.jpa:
  hibernate:
    connection:
      charset: utf8
      useUnicode: true
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true
