server:
  port: 8202

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://condonuityuatdb.mysql.database.azure.com:3306/condonuityuat?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: condonuity@condonuityuatdb
    password: '{cipher}a95eb33f0871e22c604be42de04f190d97955b68c837f2d306098bccd063b89c'

spring.jpa:
  hibernate:
    connection:
      charset: utf8
      useUnicode: true
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
