server:
  port: 8202

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://condonuity-uat-db.mysql.database.azure.com:3306/condonuityuat?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: condonuity@condonuity-uat-db
    password: '{cipher}798161371b66572a9dce2303c9236bf83d161e5b1ed797dba762828907b24198'

spring.jpa:
  hibernate:
    connection:
      charset: utf8
      useUnicode: true
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
